name: solve

on:
  push:
    branches:
      - master

jobs:
  solve:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        day: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
        part: [1, 2]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      - run: npm start --day=${{matrix.day}} --part=${{matrix.part}}
